describe('Pizza Order App', () => {
    beforeEach(() => {
        cy.visit('http://localhost:3003/pizza');
    });
    const nameInput = () => cy.get('input[name = "name"]')
    const pepperoni = () => cy.get('input[name = "pepperoni"]')
    const sausage = () => cy.get('input[name = "sausage"]')
    const canadianBacon = () => cy.get('input[name = "canadianBacon"]')
    const spicyItalianSausage = () => cy.get('input[name = "spicyItalianSausage"]')
    const grilledChicken = () => cy.get('input[name = "grilledChicken"]')
    const onions = () => cy.get('input[name = "onions"]')
    const greenPepper = () => cy.get('input[name = "greenPepper"]')
    const dicedTomatos = () => cy.get('input[name = "dicedTomatos"]')
    const blackOlives = () => cy.get('input[name = "blackOlives"]')
    const roastedGarlic = () => cy.get('input[name = "roastedGarlic"]')
    const artichokeHearts = () => cy.get('input[name = "artichokeHearts"]')
    const threeCheese = () => cy.get('input[name = "threeCheese"]')
    const pineapple = () => cy.get('input[name = "pineapple"]')
    const extraCheese = () => cy.get('input[name = "extraCheese"]')
    const instructions = () => cy.get('textarea[name = "specialInstructions"]')
    const submitButton = () => cy.get('#submitBtn');

    it('add text to instruction', () => {
        instructions()
            .should("have.value", "")
            .type("Stone Cogswell")
            .should("have.value", "Stone Cogswell")
    })
    it('test that you can select multiple toppings', () => {
        pepperoni()
            .click()
        sausage()
            .click()
        canadianBacon()
            .click()
        spicyItalianSausage()
            .click()
        grilledChicken()
            .click()
        onions()
            .click()
        greenPepper()
            .click()
        dicedTomatos()
            .click()
        blackOlives()
            .click()
        roastedGarlic()
            .click()
        artichokeHearts()
            .click()
        threeCheese()
            .click()
        pineapple()
            .click()
        extraCheese()
            .click()
    })
    it('test that form can be submitted', () => {
        nameInput()
            .should("have.value", "")
            .type("Stone Cogswell")
            .should("have.value", "Stone Cogswell")
        instructions()
            .should("have.value", "")
            .type("Stone Cogswell")
            .should("have.value", "Stone Cogswell")
        pepperoni()
            .click()
        sausage()
            .click()
        canadianBacon()
            .click()
        spicyItalianSausage()
            .click()
        grilledChicken()
            .click()
        onions()
            .click()
        greenPepper()
            .click()
        dicedTomatos()
            .click()
        blackOlives()
            .click()
        roastedGarlic()
            .click()
        artichokeHearts()
            .click()
        threeCheese()
            .click()
        pineapple()
            .click()
        extraCheese()
            .click()
        submitButton()
            .click()
    })
}) 